### PR TITLE
linechart fixed

### PR DESCRIPTION
**Pull request by aiyer786**
Week history data fixed. Dates appear in ascending order with current date as reference point in the middle.

### CODE REVIEW

**Review by shashank-madan — CHANGES_REQUESTED** [review]
Pie chart not visible anymore.
User food consumption cards not loading.

**Comment by aiyer786** [comment]
The issue is fixed. Please review again.

**Comment by shashank-madan** [comment]
> The issue is fixed. Please review again.

Still not loading the food consumption cards or pie chart.

**Comment by shashank-madan** [comment]
> > The issue is fixed. Please review again.
> 
> Still not loading the food consumption cards or pie chart.

Issue fixed.
Please remove legend from piechart card.

**Review by shashank-madan — APPROVED** [review]

**Pull request merged**
